% Z=imread('zebra.png')
% %imtool(Z)
% jnf= imresize(Z,[78,78],'nearest','antialiasing',false)
% %imtool(jnf)
% imhist(jnf)
% jnt= imresize(Z,[78,78],'nearest','antialiasing',true)
% %imtool(jnt)
% imhist(jnt)
% jbt= imresize(Z,[78,78],'bilinear','antialiasing',true)
% jbf= imresize(Z,[78,78],'bilinear','antialiasing',false)
% imtool(jbt)
% imtool(jbf)


C=imread('cameraman.png')
cnf=imresize(C,[78,78],'nearest','antialiasing',false)
cnd=imresize(C,[78,78],'nearest','antialiasing',true)
cbt=imresize(C,[78,78],'bilinear','antialiasing',true)
cbf=imresize(C,[78,78],'bilinear','antialiasing',false)
imtool(cbt)
imtool(C)
imtool(cbf)
imtool(cnd)